plugins {
    id 'com.android.application'
}

android {
    namespace 'com.samuray.telegram.sample'
    compileSdk 35

    defaultConfig {
        applicationId 'com.samuray.telegram.sample'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':telegram-tdlib')
}
